language: perl
perl:
    - 5.10
cache:
    - apt
    - ccache
services:
    - redis-server
env:
    global:
        - V_OPENRESTY=1.13.6.1
install:
    - cpanm -v --notest Test::Nginx
before_script:
    - sudo apt-get update -q
    - sudo apt-get install libreadline-dev libncurses5-dev libpcre3-dev libssl-dev -y
    - sudo apt-get install make build-essential lua5.1 -y
    - wget https://openresty.org/download/openresty-$V_OPENRESTY.tar.gz
    - tar xzf openresty-$V_OPENRESTY.tar.gz
    - cd openresty-$V_OPENRESTY && ./configure && make && sudo make install && cd ..
    - git clone https://github.com/tokers/lua-resty-http2
    - cp -r lua-resty-http2/lib/resty/http2 /usr/local/openresty/lualib/resty
    - cp lua-resty-http2/lib/resty/http2.lua /usr/local/openresty/lualib/resty
script:
    - make test
